<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Optimize>true</Optimize>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <DebugType>portable</DebugType>
    <Version>1.0.0</Version>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GameDir>D:\SteamLibrary\steamapps\common\7 Days To Die</GameDir>
    <GameManagedDir>$(GameDir)\7DaysToDie_Data\Managed</GameManagedDir>
    <GameModsDir>$(GameDir)\Mods</GameModsDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameManagedDir)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameManagedDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(GameManagedDir)\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="LogLibrary">
      <HintPath>$(GameManagedDir)\LogLibrary.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(GameModsDir)\0_TFP_Harmony\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GearsAPI">
      <HintPath>GearsAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="netstandard">
      <HintPath>$(GameManagedDir)\netstandard.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.Addressables">
      <HintPath>$(GameManagedDir)\Unity.Addressables.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
